"""ActivityWatch watcher for laptop lid events and system suspend/resume."""

try:
    # Generated by hatch-vcs at build/install time
    from ._version import __version__
except ImportError:  # running from a source checkout that was never installed
    __version__ = "0+unknown"

__all__ = ["__version__"]
